name: CI
on:
  pull_request:
  push:
    branches: [master]
jobs:
  precommit:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.18.3"
          otp-version: "27.3"
      - uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: mix-${{ runner.os }}-${{ hashFiles('mix.lock') }}
      - run: mix deps.get
      - run: mix precommit
